# 🔹 NumPy (Numerical Python)

**NumPy** is a powerful Python library used for numerical computing and working with arrays.

---

## 🔹 Key Features
- Provides fast and efficient **array operations**  
- Supports **multi-dimensional arrays**  
- Includes mathematical and statistical functions  
- Optimized for performance (faster than lists)  

---

## 🔹 Core Concept
- **ndarray (N-dimensional array)** → Main data structure in NumPy  
- Stores elements of the same data type  
- Allows vectorized operations  

---

## 🔹 Common Uses
- Data analysis  
- Scientific computing  
- Machine learning  
- Matrix operations  

---

## 🔹 Advantages
- Faster computation  
- Less memory usage  
- Easy mathematical operations  
- Supports broadcasting  

---

## 🔹 NumPy vs Python List

| Feature        | NumPy Array        | Python List       |
|----------------|------------------|------------------|
| Speed          | Faster            | Slower           |
| Memory         | Efficient         | More usage       |
| Data Type      | Same type         | Mixed types      |
| Operations     | Vectorized        | Manual loops     |

---

## 🔹 Summary

NumPy is used for **fast and efficient numerical operations**, especially with arrays and mathematical computations.

In [1]:
arr = [1,2,3]
print(arr * 5)

arr = [x * 5 for x in arr]
print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [3]:
import numpy as np
arr1 = np.array([1,2,3])
arr1 = arr1 * 5
print(arr1)

[ 5 10 15]


## Nd Array

In [11]:
import numpy as np
# 1D Array:
arr1 = np.array([1,2,3,4,5])
print(type(arr1))
print(arr1.ndim)

# 2D Array

arr2 = np.array([[1,2,3], # Row 1
                 [4,5,6] # Row 2
                ])
print(arr2.ndim)

# 3D Array - ekta Array er vitor onkgula 2D array

arr3 = np.array([
        [ # 1st Floor
        [1,2,3],
        [4,5,6] 
        ],
        [ #2nd Floor
        [1,2,3], 
        [4,5,6]
        ]
                ]
               )
print(arr3.ndim)

<class 'numpy.ndarray'>
1
2
3


## Array Attributes

In [13]:
## Array-dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

# Shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

# Data-Type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

# Size
print(arr1.size)
print(arr2.size)
print(arr3.size)


1
2
3
(5,)
(2, 3)
(2, 2, 3)
int64
int64
int64
5
6
12


## Ndarray Data Types

In [16]:
arr = np.array([1,2,3])
print(arr.dtype)
arr = np.array([1,2,3,2.4])
print(arr.dtype)


int64
float64


In [25]:
arr = np.array([1,2,3,2.4])
# upcasted to float
print(arr.dtype)
arr = np.array([1,2,3,2.4,'3'])
# Upcasted to String
print(arr.dtype)

float64
<U32


# selecting a Data Type for an Array

In [24]:
arr = np.array([1,2,3], dtype = np.int8)
print(arr.dtype)
# another way
arr = arr.astype(np.int16)
print(arr.dtype)

int8
int16


## NdArray Creation From existing Data

In [29]:
#list
lst = [10,20,30,40]
arr = np.array(lst)
print(arr)
print(type(arr))
print(arr.dtype)

mixed_lst = [10,True,'Hello', 10.5]
arr = np.array(mixed_lst)
print(arr)
print(type(arr))
print(arr.dtype)


[10 20 30 40]
<class 'numpy.ndarray'>
int64
['10' 'True' 'Hello' '10.5']
<class 'numpy.ndarray'>
<U32


In [30]:
# MAtrix
matrix = [[1,2,3], # Row 1
          [4,5,6] # Row 2
                ]
arr = np.array(matrix)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
2
(2, 3)


In [31]:
# Tuple
tpl = (10,20,30)
arr = np.array(tpl)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

[10 20 30]
<class 'numpy.ndarray'>
int64
1
(3,)


In [33]:
# set
st = {1,2,3}
arr = np.array(st)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

st = {1,2,3}
arr = np.array(list(st))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

{1, 2, 3}
<class 'numpy.ndarray'>
object
0
()
[1 2 3]
<class 'numpy.ndarray'>
int64
1
(3,)


In [36]:
# Dictionary
dc = {'a' : 10, 'b' : 20, 'c' : 30}
keys = dc.keys()
values = dc.values()
items = dc.items()
print(keys)
print(values)
print(items)



dict_keys(['a', 'b', 'c'])
dict_values([10, 20, 30])
dict_items([('a', 10), ('b', 20), ('c', 30)])


In [37]:
# Keys To nDarray
arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
1
(3,)


In [39]:
# Values to ndarray
arr = np.array(list(values))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

[10 20 30]
<class 'numpy.ndarray'>
int64
1
(3,)


In [40]:
# items to ndarray
arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
2
(3, 2)


## ndarray creation from scratch

In [49]:
# np.zeroes
arr = np.zeros((2,3), dtype = np.int8) # With row and column
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.zeros_like(arr3) # In the first we take a 3d array
print(arr)
print(arr.shape)

[[0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
int8
(2, 3)
2
6
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(2, 2, 3)


In [52]:
# np.ones
arr = np.ones((2,3), dtype = np.int8) # With row and column
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.ones_like(arr3) # In the first we take a 3d array
print(arr)
print(arr.shape)

[[1 1 1]
 [1 1 1]]
<class 'numpy.ndarray'>
int8
(2, 3)
2
6
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(2, 2, 3)


In [71]:
# Empty
arr = np.empty((2,3), dtype = np.int8) # With row and column any data can occurs
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.empty_like(arr3) # In the first we take a 3d array
print(arr)
print(arr.shape)

[[1 1 1]
 [1 1 1]]
<class 'numpy.ndarray'>
int8
(2, 3)
2
6
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(2, 2, 3)


In [76]:
# np.full
arr = np.full((2,3),np.inf)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.full_like(arr3, np.inf, dtype = np.float64) # In the first we take a 3d array which data type was int64 bit
print(arr)
print(arr.shape)

[[inf inf inf]
 [inf inf inf]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6
[[[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]]
(2, 2, 3)


## ndarray Generation With Random Values

In [79]:
# np.random.rand(shape)
arr = np.random.rand(2,3) # value provide between 1 and 0
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0.19331502 0.27120302 0.59643624]
 [0.66357102 0.71099278 0.63284989]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [82]:
# np.random.rand(start, end, shape)
arr = np.random.randint(1,10,(2,3)) # value provide between 1 and 10 and shape is 2 by 3
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[1 4 5]
 [4 4 4]]
<class 'numpy.ndarray'>
int32
(2, 3)
2
6


In [84]:
# np.random.uniform(start, end, shape)
arr = np.random.uniform(50,100,(2,3)) # value provide between 1 and 10 and shape is 2 by 3
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[64.63753944 83.00954744 94.61819852]
 [87.91580643 53.43002327 58.36292629]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


## ndarray creation from range

In [85]:
# np.arange(first, end, step) -> similar to range function
arr = np.arange(1, 10, 1)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [87]:
# reshape
arr = np.arange(1, 10, 1).reshape(3,3) # We Can Convert into Matrix
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(3, 3)
2
9


## 🔹 linspace vs logspace

| Feature  | `linspace` 🟦    | `logspace` 🟧             |
|----------|------------------|---------------------------|
| Spacing  | Linear           | Logarithmic               |
| Pattern  | Equal difference | Equal ratio (multiplying) |
| Use case | Normal ranges    | Exponential/log scales    |
| Example  | 1, 2, 3, 4       | 10, 100, 1000             |

In [90]:
# np.linespace(stary, end(included), total_point)
arr = np.linspace(1, 10, 10) # -> divide the line equally according to total_point
print(arr)

arr = np.linspace(1, 10, 11) # -> divide the line equally according to total_point
print(arr)




[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1 10. ]


In [95]:
# np.logspace(start, end(included), total_point)
arr = np.logspace(1, 4, 5) # -> 10 to the power point
print(arr)

arr = np.logspace(1, 4, 5, base = 2) # -> 2 to the power point
print(arr)

[   10.            56.23413252   316.22776602  1778.27941004
 10000.        ]
[ 2.          3.36358566  5.65685425  9.51365692 16.        ]


## Creating Diagonal and Identity Matrix

## 🔹 Diagonal vs Identity Matrix (Difference)

| Feature         | Diagonal Matrix 🟦        | Identity Matrix 🟧        |
|-----------------|---------------------------|---------------------------|
| Diagonal values | Any number                | Always 1                  |
| Type            | General matrix            | Special case of diagonal  |
| Example         | 5, 3, 8 (on diagonal)     | 1, 1, 1 (on diagonal)     |

In [96]:
diagonal_matrix = np.diag([1,2,3])
print(diagonal_matrix)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [100]:
identity_matrix = np.eye(3)
print(identity_matrix)

# np.eye(row, column, k)
identity_matrix = np.eye(3, 4, -1) # -> for -1 it will shift to lower anf for 1 it will shift to upper
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


## ndarray indexing and slicing

In [103]:
# indexing
# print(arr1)
# print(arr2)

print(arr1[2])

3


In [106]:
# Slicing
# for 1d array = arr[start:end:step]
arr1_mod = arr1[1:4] # -> step by default 1...and if i changes in arr1_mod it will reflect in main array it just view of main array if we want to coppy we have to add .copy()

print(arr1_mod)

[2 3 4]


In [111]:
# 2d array -> arr[row_start :row_end :step, column_start :column_end :step]

# getting a row
row_0 = arr2[0:1,]
row_1 = arr2[1: ,]
print(row_0)
print(row_1)

#By same We can get columns
col_0 = arr2[:, 0:1]
print(col_0)

[[1 2 3]]
[[4 5 6]]
[[1]
 [4]]


## ndarray Copy Advanced Indexing and Iteration

In [116]:
lst = np.array([10, 20, 30, 40])
values = lst[[1,3]]
print(values)


[20 40]


In [120]:
print(arr2[[0,1], [1,2]])
print(arr2[arr2 > 2]) # -> By Boolean
arr2[arr2 >2] = 0

[2 6]
[3 4 5 6]


In [123]:
arr = np.array([[10,20,30], [100,200,300]])

#iteration
for i in np.nditer(arr): # We dont have to use nested loop
    print(i)

10
20
30
100
200
300
