# 🔹 Data Analysis with NumPy

**NumPy** is widely used for data analysis due to its fast array operations and powerful mathematical functions.

---

## 🔹 Key Concepts
- **Array Creation** → Convert data into NumPy arrays  
- **Indexing & Slicing** → Access and filter data  
- **Vectorized Operations** → Perform calculations without loops  
- **Broadcasting** → Operate on arrays of different shapes  

---

## 🔹 Common Operations
- **Aggregation** → sum(), mean(), median(), min(), max()  
- **Statistical Analysis** → standard deviation, variance  
- **Sorting & Filtering** → sort data, apply conditions  
- **Reshaping** → change array structure  

---

## 🔹 Why Use NumPy for Data Analysis
- Faster than traditional Python lists  
- Handles large datasets efficiently  
- Simplifies complex mathematical operations  
- Forms the base for libraries like Pandas  

---

## 🔹 Example Idea
- Load data → Convert to array → Analyze → Get insights  

---

## 🔹 Summary

NumPy helps perform **fast, efficient, and scalable data analysis using arrays and mathematical operations**.

## numpy array manipulation

In [41]:
import numpy as np
arr = np.random.randint(1, 100, size = (10, 5))

In [42]:
arr.shape

(10, 5)

In [43]:
# Changing The Shape
b = arr.reshape(5, 10) # -> if you want to covert into 3*5 it will be invalid ..unable to hold 50 values 
b.shape

(5, 10)

In [44]:
# covert into 1 dimension
row_flatten = b.flatten() # -> Convert Row Wise
print(flatten)

[93 66 51 85 68 79 35 65 87 68 21 22 99 25 45 92 58 29 25 38 81 18  6 82
 21 89 70 92 22 42 90 78 99 93 19 76 54 92 58 86 82 65 40 63  6 97 95 28
 63 58]


In [45]:
column_flattening = np.ravel(b, order = 'F') # -> if we give order = 'C' it will work row wise
print(column_flattening)

[83  9  4  7 12 71 37 16 43 29 92 88 98 99 64 24 38  8 48 95 93 77 21 79
 15 64 72 86 29  5 47  8 55 69  6 66 30 43 73 41 86 61 86 33 80 59 32 70
 22 62]


In [46]:
a = np.random.randint(1, 10, size = (2, 3))
b = np.random.randint(20, 30, size = (2, 3))
print(a)
print(b)

[[3 7 3]
 [3 7 8]]
[[25 20 29]
 [22 26 23]]


In [47]:
# Concatenate -> shape must be under consideration
con_row = np.concatenate((a, b), axis = 0) # -> Row Wise - > Column must be same
print(con_row)
con_col = np.concatenate((a, b), axis = 1) # -> Column Wise -> row must be same
print(con_col)

[[ 3  7  3]
 [ 3  7  8]
 [25 20 29]
 [22 26 23]]
[[ 3  7  3 25 20 29]
 [ 3  7  8 22 26 23]]


In [48]:
# Transpose
mat = np.array([[10, 20, 30],
                [30, 40, 50]    
])
transpose = mat.T
print(transpose)

[[10 30]
 [20 40]
 [30 50]]


In [49]:
# Array Split
a = np.random.randint(1, 10, size = (12, ))
print(a)
splitted_array = np.array_split(a, 3)
print(splitted_array)
splitted_array = np.split(a, 4) # -> must be divided into equal division or it will throw an error
print(splitted_array)

[1 3 5 8 8 2 5 8 2 1 7 2]
[array([1, 3, 5, 8], dtype=int32), array([8, 2, 5, 8], dtype=int32), array([2, 1, 7, 2], dtype=int32)]
[array([1, 3, 5], dtype=int32), array([8, 8, 2], dtype=int32), array([5, 8, 2], dtype=int32), array([1, 7, 2], dtype=int32)]


## ndaraay Arithmatic operators and mathematical Functions

In [50]:
x = np.array([10, 20, 30, 40])
y = np.array([2, 3, 4, 5])
add = x + y # -> np.add(x,y)
print(add)

sub = x - y
print(sub)

mul = x * y
print(mul)

div = x / y
print(div)

remainder = x % y
print(remainder)

[12 23 34 45]
[ 8 17 26 35]
[ 20  60 120 200]
[5.         6.66666667 7.5        8.        ]
[0 2 2 0]


In [51]:
# Mathmatical Functions
# trigonometry
sin_val = np.sin(x) # -> values in radian
print(sin_val)

cos_val = np.cos(x) # -> values in radian
print(sin_val)

deg_conversion = np.rad2deg(x) # -> degrre to radian
print(deg_conversion)

[-0.54402111  0.91294525 -0.98803162  0.74511316]
[-0.54402111  0.91294525 -0.98803162  0.74511316]
[ 572.95779513 1145.91559026 1718.87338539 2291.83118052]


In [52]:
# logarithmic
base_10_log_values = np.log10(x)
print(base_10_log_values)

base_2_log_values = np.log2(x)
print(base_2_log_values)

sqrt = np.sqrt(x)
print(sqrt)

[1.         1.30103    1.47712125 1.60205999]
[3.32192809 4.32192809 4.9068906  5.32192809]
[3.16227766 4.47213595 5.47722558 6.32455532]


# Mathematical Functions - https://numpy.org/doc/2.4/reference/routines.math.html

In [53]:
# sum
s = np.sum(x)
print(s)

# prefix Sum er moto
cumulative_Sum = np.cumulative_sum(x)
print(cumulative_Sum)

100
[ 10  30  60 100]


## Numpy Logical Functions

In [57]:
x = np.array([10, 20, 30, 40])
y = np.array([2, 3, 4, 5])

greater_then = x > y
print(greater_then)

equal = x == y
print(equal)

# all() -> is all True?
# any() -> if one is True?

print(np.all(greater_then))
print(np.any(equal))

[ True  True  True  True]
[False False False False]
True
False


## ndarray sorting

In [59]:
# inplace sorting -> prebious version will not be avilable
x = np.array([50, 20, 10, 40])
z = x.copy()
z.sort()
print(z)

[10 20 40 50]


In [60]:
# copy Sorting
sort_arr = np.sort(x)
print(x)
print(sort_arr)

[50 20 10 40]
[10 20 40 50]


In [62]:
# 2d array sorting - row wise sort or column wise sort
mat = np.array([
    [10, 3, 5],
    [8, 4, 9]
])
row_sort = np.sort(mat, axis = 1)
print(row_sort)
col_sort = np.sort(mat, axis = 0)
print(col_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


## Ndarray Searching

In [63]:
print(x)

[50 20 10 40]


In [70]:
# np.where(condition, x, y) if true x, otherwise replace with y

index = np.where(x == 40)
print(index)

index = np.where(x > 5)
print(index)

array = np.where(x > 40, x, 0) # it will return an array
print(array)

(array([3]),)
(array([0, 1, 2, 3]),)
[50  0  0  0]


In [69]:
print(mat)

[[10  3  5]
 [ 8  4  9]]


In [74]:
index = np.where(mat > 8) # the value of (0, 0) and (1, 2) are greater then 8
print(index)

array = np.where(mat > 40, mat, 0) # it will return an array
print(array)

(array([0, 1]), array([0, 2]))
[[0 0 0]
 [0 0 0]]


In [76]:
maximum_index = np.argmax(x)
print(maximum_index) # return index

0


In [78]:
minimum_index = np.argmin(x)
print(minimum_index) # return index

2


## ndarray counting

In [81]:
a = np.random.randint(1, 100, size = (100, ))
print(a)

[74 13 22 32 14 40 83 76 47 61 20 15 52 18 78 50 45 81 20  7 58 26 75 43
 50 35 28  9 22 10  6 74 12  7 87 53 32 49 85 27 47 31 69 99 21  4 38 15
 53  2 65 71 41  5 11 49 63 35 66 16 68 62 94 58 52 12 63 76 73 69  4 80
 39 26  4 50 68 55 93 68 35 85 41 14 54  7 26 83 21 85 19 25 67 76 72 19
 36 76 96 64]


In [90]:
value_greater_then = np.count_nonzero(a == 13)
print(value_greater_then)

1


In [88]:
unique_values, count = np.unique(a, return_counts = True)
print(unique_values)
print(count)

[ 2  4  5  6  7  9 10 11 12 13 14 15 16 18 19 20 21 22 25 26 27 28 31 32
 35 36 38 39 40 41 43 45 47 49 50 52 53 54 55 58 61 62 63 64 65 66 67 68
 69 71 72 73 74 75 76 78 80 81 83 85 87 93 94 96 99]
[1 3 1 1 3 1 1 1 2 1 2 2 1 1 2 2 2 2 1 3 1 1 1 2 3 1 1 1 1 2 1 1 2 2 3 2 2
 1 1 2 1 1 2 1 1 1 1 3 2 1 1 1 2 1 4 1 1 1 2 3 1 1 1 1 1]


## Statistical Function

In [92]:
# Data Load
data = np.genfromtxt('student_scores.csv', delimiter = ',', skip_header = 1)
print(data)

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [98]:
math_marks = data[::, : 1]
print(math_marks.T) # -> Show the Result Row Wise

max_math_marks = np.max(math_marks)
print(max_math_marks)

min_math_marks = np.min(math_marks)
print(min_math_marks)

average_math_marks = np.mean(math_marks)
print(average_math_marks)

median_math_marks = np.median(math_marks)
print(median_math_marks)

# Standard Deviation
std_math_marks = np.std(math_marks)
print(std_math_marks)

[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
95.0
45.0
73.15
73.5
13.788672887555204


## linear Algebra with numpy - https://numpy.org/doc/2.2/reference/routines.linalg.html

In [99]:
study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 92])

data = np.array([study_hours, exam_scores])

correlation = np.corrcoef(data)

print("Correlation Matrix:\n", correlation)

Correlation Matrix:
 [[1.         0.99859154]
 [0.99859154 1.        ]]


In [101]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])
dot_product = np.dot(A, B)
print(dot_product)

print(np.trace(B)) # -> Summation of diagonal elements




[[ 58  64]
 [139 154]]
17


In [103]:
# determinent -> matrix must be square
sq_mat = np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]
])

det_of_sq_mat = np.linalg.det(sq_mat)
print(det_of_sq_mat)

6.66133814775094e-16


In [104]:
# rank of matrix
rank_of_sq_mat = np.linalg.matrix_rank(sq_mat)
print(rank_of_sq_mat)

2
